
services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "80:3000"
    environment:
      - WEFREI_API_KEY=${WEFREI_API_KEY}
      - ADMIN_PASS=${ADMIN_PASS}
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    restart: unless-stopped
